version: 2
project_name: gclone

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gclone
    binary: gclone
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: gclone
    repository:
      owner: rickyseezy
      name: homebrew-gclone
    directory: Formula
    homepage: "https://github.com/rickyseezy/gclone"
    description: "Clone git repositories using SSH profile aliases."
    install: |
      bin.install "gclone"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
